(if (y-or-n? "Load Shen Standard Library? ")
    (do (cd "Lib/StLib")
        (load "install.shen"))
    skip)

(if (y-or-n? "Load Concurrent Shen? ")
    (do (cd "Lib/Concurrency")
        (tc -)
        (load "concurrency.dtype")
        (tc +)
        (load "concurrency.shen"))
     skip)

(if (and (package? p) (y-or-n? "Load TCL/tk + IDE? "))
    (do (cd "Lib/Tk")
        (tc -)
        (load "loadme.shen")
        (cd "Lib/IDE")
        (load "idedec.shen")
        (tc +)
        (load "ide.shen"))
    skip)
           
(if (y-or-n? "Load THORN (high-speed theorem-prover)? ")
    (do (cd "Lib/THORN")
        (tc -)
        (load "datatypes.shen")
        (load "THORN20.shen"))
     skip)
           
(if (y-or-n? "Load Logic Lab?")
    (do (cd "Lib/LogicLab")
           (tc -)
           (load "compiler.shen")
           (tc +)
           (load "gpa.shen"))
    skip) 
           
(cd "")
(tc -) 