(tc -)
(if (= (language) "Scheme") (load "patches-scheme.shen") skip)

(if (y-or-n? "install standard library?")
    (do (cd "Lib/StLib")
        (load "install.shen"))
    skip)    
        
(if (and (package? stlib) (= (language) "Common Lisp") (y-or-n? "install concurrency? (required for Shen/tk)"))
    (do (tc -)
        (cd "Lib/Concurrency")
        (load "concurrency.dtype")
        (tc +)
        (load "concurrency.shen"))
     skip)

(if (and (package? p) (y-or-n? "install Shen/tk + IDE?"))
    (do (tc -)
        (cd "Lib/Tk")
        (load "loadme.shen")
        (tc -)
        (cd "Lib/IDE")
        (load "idedec.shen")
        (tc +)
        (load "ide.shen")
        (tk.types -))
     skip)

(if (and (package? stlib) (y-or-n? "install THORN?"))
    (do (cd "Lib/THORN")
        (tc -)
        (load "datatypes.shen")
        (load "THORN20.shen"))
     skip)
           
(if (and (package? stlib) (y-or-n? "install Logic Lab?"))
    (do (cd "Lib/LogicLab")
        (tc -)
        (load "compiler.shen")
        (tc +)
        (load "gpa.shen"))
     skip)
    
(preclude-all-but [])
(set shen.*userdefs* [])
(cd "") 
(tc -)
(if (= (language) "Scheme") (ide.myIDE) skip)